# Generated by Django 3.0.4 on 2020-04-07 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutella', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
